name: artifacts upload workflow

on:
  push:
    branches: [ "master" ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/artifact/world.txt

      - uses: actions/download-artifact@v4
        id: test
        with:
          name: my-artifact
          path: path/to/artifacts

      - name: 'Echo download path'
        env:
          DOWNLOAD_PATH: ${{ steps.test.outputs.download-path }}
        run: echo "$DOWNLOAD_PATH"

      - name: 'Cat world.txt'
        env:
          DOWNLOAD_PATH: ${{ steps.test.outputs.download-path }}
        run: cat "$DOWNLOAD_PATH/world.txt"
